export const GET_BLOCK_LIST = 'GET_BLOCK_LIST';
export const GET_BLOCK_DETAILS_SUCCESS = 'GET_BLOCK_DETAILS_SUCCESS';
export const GET_BLOCK_LIST_SUCCES = 'GET_BLOCK_LIST_SUCCES';
export const GET_BLOCK_PAGE_ERROR = 'GET_BLOCK_PAGE_ERROR';
export const ERROR = 'ERROR';

